CREATE TABLE apptrackr_applications (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    job_name TEXT NOT NULL,
    company_name TEXT NOT NULL,
    website_url TEXT,
    date_applied TEXT,
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    interview_date TEXT,
    status TEXT NOT NULL,
    notes TEXT,
    user_id INTEGER REFERENCES apptrackr_users(id) ON DELETE CASCADE NOT NULL
);