CREATE TABLE apptrackr_resources (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    resource_name TEXT NOT NULL,
    resource_url TEXT NOT NULL,
    type TEXT NOT NULL,
    notes TEXT,
    user_id INTEGER REFERENCES apptrackr_users(id) ON DELETE CASCADE NOT NULL
);